accounts/urls.py
from django.urls import path
from .import views

app_name= 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

    # profile
    path('<username>/', views.profile, name='profile'),
    path('<username>/follow/', views.follow, name='follow'),
]

insta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static # url이 들어올때 어느 경로로 가야 하는지
from django.conf import settings
from posts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('', views.index)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #concat / 경로 - 저장한 실제 위치

posts/urls.py
from django.urls import path
from .import views

app_name = 'posts'

urlpatterns = [
    path('',views.index, name = 'index'),
    path('create/', views.create, name='create'),
    #comment
    path('<int:post_id>/comments/create/', views.comment_create, name='comment_create'),
    path('<int:post_id>/like/', views.like, name='like'),
    path('feed/', views.feed, name='feed'),
    path('<int:id>/like-async/', views.like_async, name='like_async'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django_resized import ResizedImageField

# Create your models here.

# 유저
class User(AbstractUser):
    # username
    # passward
    profile_image = ResizedImageField(
        size = [500,500],
        crop = ['middle', 'center'],
        upload_to = 'profile',
    )
    # post_set
    # comment_set
    # post_set => like_posts(MMF)
    followings = models.ManyToManyField('self', related_name ='followers', symmetrical=False) # 반대쪽에서 어떻게 부를지
    # user_set(반대쪽) => followers(user_set 이름 변경)
    # symmetrical=False : 비대칭구조 (1-> 2 팔로우 / 2 ->1 팔로우는 다르기 때문)

posts/models.py
from django.db import models
from django_resized import ResizedImageField
from django.conf import settings

# Create your models here.

# 게시글
class Post(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add = True)
    # image = models.ImageField(upload_to = 'image') # image 폴더 생성 후 그 안에 이미지 저장됨 / pillow 설치 !
    image = ResizedImageField(
        size = [500,500], 
        crop = ['middle', 'center'], # 가운데 기준 크롭
        upload_to = 'image/%Y/%m', # 연도와 월을 기준으로 폴더를 만듦.
    )
    # 작성자 연결
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    
    # 좋아요를 누른 사람 연결
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, 
        related_name='like_posts',
        ) # User와 Post를 M:N으로 연결

# 댓글
class Comment(models.Model):
    content = models.CharField(max_length=200)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import User

# 회원가입
class CustomUserCreationForm(UserCreationForm):
    class Meta():
        model = User
        fields = ('username', 'profile_image', )

# 로그인
class CustomAuthenticationForm(AuthenticationForm):
    pass

posts/forms.py
from django.forms import ModelForm
from .models import Post, Comment

class PostForm(ModelForm):
    class Meta():
        model = Post
#        fields = '__all__'
        fields = ('content', 'image',)

class CommentForm(ModelForm):
    class Meta():
        model = Comment
        fields = ('content',)

accounts/views.py
from django.shortcuts import render,redirect
from .forms import CustomUserCreationForm,CustomAuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from .models import User
from django.contrib.auth.decorators import login_required

# Create your views here.

def signup(request):
    if request.method == 'POST':
        pass
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('posts:index')
    else:
        form = CustomUserCreationForm()

    context = {
        'form':form,
    }
    return render(request, 'signup.html', context)

def login(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()   # id, passward에 맞는 사용자 정보 가져오기
            auth_login(request, user)
            return redirect ('posts:index')
    else:
        form = CustomAuthenticationForm()

    context = {
        'form':form,
    }
    return render(request, 'login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('posts:index')

def profile(request, username):
    user_profile = User.objects.get(username=username) # user와 충돌해서 변수 이름 변경

    context = {
        'user_profile':user_profile,
    }

    return render(request, 'profile.html', context)

@login_required
def follow(request, username):
    me = request.user
    you = User.objects.get(username=username)

    if me==you: # 스스로 팔로우하는 것 방지 (백엔드)
        return redirect('accounts:profile', username)

#   if you in me.followings.all():
    if me in you.followers.all():
        you.followers.remove(me)
        #me.followings.remove(you)
    else:
#        you.followers.add(me)
        me.followings.add(you)
    return redirect('accounts:profile', username)

posts/views.py
from django.shortcuts import render,redirect
from .models import Post,Comment
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse       # dict 주면 ---> json으로 바꿔줌

# Create your views here.

def index(request):
    posts = Post.objects.all()
    form = CommentForm()
    context = {
        'posts':posts,
        'form':form,
    }
    return render(request, 'index.html', context)

@login_required
def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)   # 유저 정보가 빠져있음.
            post.user = request.user
            post.save()
            return redirect('posts:index')
    
    else:
        form = PostForm()
    context = {
        'form':form,
    }

    return render(request, 'create.html', context)

@login_required
def comment_create(request, post_id):
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.user = request.user
        comment.post_id = post_id # 댓글 달 게시글 찾기
        comment.save()
        return redirect('posts:index')

@login_required
def like(request, post_id):
    user = request.user
    post = Post.objects.get(id=post_id)

#1) 유저 관점
    if user in post.like_users.all(): # 좋아요가 눌려 있으면 좋아요 제거
        post.like_users.remove(user)   
    else:
        post.like_users.add(user) # 좋아요 눌리지 않으면 누르기
    
    return redirect('posts:index')

#2) 게시글 관점
    # if post in user.like_posts.all():
    #     user.like_posts.remove(post)
    # else:
    #     user.like_posts.add(post)

def feed(request):
    followings = request.user.followings.all() # 내가 팔로잉 하는 사람들 목록
    posts = Post.objects.filter(user__in=followings) # 내가 팔로잉 하는 사람들이 작성한 게시글
    
    form = CommentForm()

    context = {
        'posts':posts,
        'form':form,
    }
    return render(request, 'index.html', context)

# 자바 스크립트 : 좋아요 기능

def like_async(request, id):
    user = request.user
    post = Post.objects.get(id=id)

    if user in post.like_users.all():
        post.like_users.remove(user)
        status = False
    else:
        post.like_users.add(user)
        status = True

    context = {
        'post_id': id,
        'status': status,
        'count': len(post.like_users.all())
    }
    return JsonResponse(context)

accounts/templates/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form show_label=False %}
        <input type="submit" class="btn btn-primary mt-3">
    </form>
{% endblock %}

accounts/templates/profile.html
{% extends 'base.html' %}

{% block body %}
    <div class="row my-3"> 
        <div class="col-3">
            <img src="{{user_profile.profile_image.url}}" alt="" class="img-fluid rounded-circle">
        </div> 
        <div class="col-9">
            <div class="row">
                <div class="col-3">{{user_profile.username}}</div>
                {% if user != user_profile %}
                <div class="col-9">
                    {% if user in user_profile.followers.all %}
                        <a href="{% url 'accounts:follow' user_profile.username %}" class="btn btn-secondary">팔로우 취소</a>
                    {% else %}
                        <a href="{% url 'accounts:follow' user_profile.username %}" class="btn btn-primary">팔로우</a>
                    {% endif %}
                </div>
                {% endif %}
            </div>
            <div class="row">
                <div class="col-4">게시물 : {{user_profile.post_set.all|length}}</div>
                <div class="col-4">팔로워 : {{user_profile.followers.all|length}}</div>
                <div class="col-4">팔로우 : {{user_profile.followings.all|length}}</div>
            </div>
        </div> 
    </div>
    <div class="row"> 
        {% for post in user_profile.post_set.all %}
            <div class="col-4">
                <img src="{{post.image.url}}" alt="" class="img-fluid">
            </div>
        {% endfor %}
    </div>
{% endblock %}

accounts/templates/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form show_label=False %}
        <input type="submit" class="btn btn-primary mt-3">
    </form>
{% endblock %}

posts/templates/_card.html
{% load django_bootstrap5 %}

<div class="card my-3 col-12 col-md-6 col-xl-4">
  <!-- <div class="card my-3 col-12 offset-md-2 col-md-6"> -->
    <div class="card-header">
        <img class="rounded-circle" src="{{post.user.profile_image.url}}" alt="" width="30px">
        <a href="{% url 'accounts:profile' post.user.username %}">{{post.user.username}}</a>
    </div>
    <img src="{{post.image.url}}" class="" alt="...">
    <div class="card-body">

        {% if user in post.like_users.all %}
          <i class="bi like bi-heart-fill" style="color: red;" data-post-id="{{post.id}}">
            <span style="color: orchid">{{post.like_users.all|length}}</span>
          </i>

        {% else %}
          <i class="bi like bi-heart" data-post-id="{{post.id}}">
            <span style="color: orchid">{{post.like_users.all|length}}</span>
          </i>

        {% endif %}
      <span>명이 좋아합니다.</span>
      <!-- <h5 class="card-title">Card title</h5> -->
      <p class="card-text">{{post.content}}</p>
      <p class="card_text">{{post.created_at|timesince}}</p>
      <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
    </div>
      {% if user.is_authenticated %}
    <div class="card-footer">
      <form action="{% url 'posts:comment_create' post.id %}" method="POST">
        {% csrf_token %}
        <div class="row">
          <div class="col-9">
            {% bootstrap_form form show_label=False wrapper_class='' %}
          </div>
          <div class="col-2">
            <input type="submit" class="btn btn-warning">
          </div>
        </div>
      </form>  
      {% endif %}
      <div class="mt-2">
        {% for comment in post.comment_set.all %}
          <li>{{comment.user}}:{{comment.content}}</li>
        {% endfor %}
      </div>
    </div>
</div>

posts/templates/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block body %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form show_label=False %}
        {{form}}
        <input type="submit">
    </form>
{% endblock %}

posts/templates/index.html
{% extends 'base.html' %}

{% block body %}
    <div class="row">
        {% for post in posts %}    
            {% include '_card.html' %}
        {% endfor %}
    </div>
    <script>
        let likeBtns = document.querySelectorAll('i.like')
        
        let likeRequest = async (btn, postId) => {
            let likeURL = `/posts/${postId}/like-async`
            
            let res = await fetch(likeURL)
            let result = await res.json()

            if (result.status) {
                btn.style.color = 'red'
                btn.classList.remove('bi-heart')
                btn.classList.add('bi-heart-fill')
                
            } else {
                btn.style.color = 'orchid'
                btn.classList.remove('bi-heart-fill')
                btn.classList.add('bi-heart')
            }
            btn.querySelector('span').innerHTML = result.count
        }

        likeBtns.forEach(function(likeBtn){
            likeBtn.addEventListener('click', function(e){
                const postId = e.target.dataset.postId

                likeRequest(likeBtn, postId)
            })
        })


    </script>
{% endblock %}

templates/_nav.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <i class="bi bi-instagram"></i>
        Insta
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'posts:create' %}">Create</a>
                <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                <a class="nav-link" href="{% url 'posts:feed' %}">feed</a>
                <a class="nav-link disabled" href="">{{user}}</a>
            
            {% else %}
                <a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a>
                <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>

            {% endif %}
        </div>
      </div>
    </div>
</nav>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    {% include '_nav.html' %}
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>